### ISSUE TITLE
garritfra/another

### ISSUE THREAD

**Issue by garritfra** [garritfra/seeking-maintainers.net#1]
GoDo is a test application

### Meta Information (Please fill out)

```yaml
externalIssueUrl: https://github.com/garritfra/glujs/issues/25
tags: "javascript"
shortDescription: "A test application"
```
