### ISSUE TITLE
100 Days To Offload

### ISSUE THREAD

**Issue by kevquirk** [garritfra/seeking-maintainers.net#13]
### About the project

The whole point of #100DaysToOffload is to challenge you to publish 100 posts on your personal blog in a year.

I started 100 Days as I thought it would be a fun way to engage blog owners and encourage them to write content.

**Link**: https://100daystooffload.com

### Why I need help

I have a number of personal projects, but not enough time to run them all. I'd like to hand 100 Days off in its entirety to someone who has more time to manage it.

### Skills required

HTML, CSS, Git.

### How to get in touch

You can contact me in a number of ways using [my site](https://kevq.uk.contact)

### Meta Information (Please fill out)

- [x] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [x] The title of this issue only displays the name of my project
- [x] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://100daystooffload.com"

# A short description of your project. The description text of your GitHub repo might fit here nicely
description: "100 Days To Offload is a writing challenge that asks personal blog owners to publish 100 posts to their blog in the space of a year."

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [challenge, html, css]
```
