### ISSUE TITLE
gpodder.net

### ISSUE THREAD

**Issue by fundatillus** [garritfra/seeking-maintainers.net#14]
### About the project

[gpodder.net](https://gpodder.net/) is a web service to manage your podcast subscriptions via the web. You can synchronize your devices, view status information and discover new interesting podcasts online.

**Link**: https://github.com/gpodder/mygpo

### Why I need help

This project was lovingly maintained by its original author for over 10 years. It was handed off to the community who have tried to keep it running over the past few years. We'd love to smooth out some of the rough edges and continue to provide this great service to podcast lovers all around the world!

### Skills required

Django (and Python, of course)
PostgreSQL
Redis
REST API
Ubuntu Linux
HTML/CSS
Transifex (for translations)

### How to get in touch

The best place to start is our contributor page: https://gpodder.net/contribute/

### Meta Information (Please fill out)

- [X] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [X] The title of this issue only displays the name of my project
- [X] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://github.com/gpodder/mygpo"

# A short description of your project. The description text of your GitHub repo might fit here nicely
description: "gpodder.net is a web service to manage your podcast subscriptions via the web. You can synchronize your devices, view status information and discover new interesting podcasts online."

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [django, python, webservice, rest-api, podcast]
```
