### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by garritfra** [garritfra/seeking-maintainers.net#2]
### About the project

This is a test project. It is not looking for maintainers. :)

### Meta Information (Please fill out)

- [x] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [x] The title of this issue only displays the name of my project
- [x] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://github.com/garritfra/godo"

# A short description of your project. The description text of your GitHub repo might fit here nicely
description: "Huh, it's empty around here... Are you maintaining a project? Add it to this list!"

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [foo, bar]
```
