### ISSUE TITLE
Another test

### ISSUE THREAD

**Issue by garritfra** [garritfra/seeking-maintainers.net#7]
### About the project

This is another test project

### Why I need help

Lorem Ipsum...

### Skills required

Lorem Ipsum...

### How to get in touch

Lorem Ipsum...

### Meta Information (Please fill out)

- [x] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [x] The title of this issue only displays the name of my project
- [x] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://github.com/my/repo"

# A short description of your project. The description text of your GitHub repo might fit here nicely
description: "Another test project"

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [foo, bar]
```
