### ISSUE TITLE
Objection.js

### ISSUE THREAD

**Issue by KrisLau** [garritfra/seeking-maintainers.net#72]
### About the project
I'm not the maintainer just a user that's trying to help recruit since I don't have the skills to be a maintainer. Objection.js is an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) for [Node.js](https://nodejs.org/) that aims to stay out of your way and make it as easy as possible to use the full power of SQL and the underlying database engine while still making the common stuff easy and enjoyable. 

**Link**: https://github.com/Vincit/objection.js

### Skills required
I don't know everything involved so this is my informed guess haha
- JavaScript
- TypeScript
- ORM
- SQL

### How to get in touch
Probably by commenting on this issue and tagging the current maintainer (will probably change in the future so keep an eye on latest in the thread): https://github.com/Vincit/objection.js/issues/2335

### Meta Information (Please fill out)

- [x] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [x] The title of this issue only displays the name of my project
- [x] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://github.com/Vincit/objection.js"

# A short description of your project. The description text of your GitHub repo might fit here nicely
Objection.js is an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) for [Node.js](https://nodejs.org/) that aims to stay out of your way and make it as easy as possible to use the full power of SQL and the underlying database engine while still making the common stuff easy and enjoyable.

Objection.js is built on an SQL query builder called [knex](http://knexjs.org/). All databases supported by knex are supported by objection.js. SQLite3, Postgres and MySQL are [thoroughly tested](https://travis-ci.org/Vincit/objection.js).

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [ORM, JS, JavaScript]
```
