### ISSUE TITLE
Portable-VirtualBox

### ISSUE THREAD

**Issue by runarbu** [garritfra/seeking-maintainers.net#8]
### About the project

Portable-VirtualBox is a free and open-source software tool that lets you run any operating system from a USB stick without installing separate software (runs VirtualBox from the USB stick or network drive, etc.).

### Why I need help

Unfortunately, I now have less time for open-source software development than I used to. There are also outstanding bugs that I have been unable to fix, so new eyes on thus bugs would be much appreciated.

### Skills required

General coding skills and prior experience making desktop software for Windows. Portable-VirtualBox is written in AutoIt, but prior experience is probably now necessary if you are willing to spend some time learning it. I did not know AutoIt when I did take over the project.

### How to get in touch

runarb [at] gmail [dot] com

### Meta Information (Please fill out)

- [X] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [X] The title of this issue only displays the name of my project
- [X] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://www.vbox.me/"

# A short description of your project. The description text of your GitHub repo might fit here nicely
description: "Portable-VirtualBox is a free and open source software tool that lets you run any operating system from a usb stick without separate installation."

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [VirtualBox, Windows, AutoIt]
```
