### ISSUE TITLE
Smix Eleventy Starter

### ISSUE THREAD

**Issue by MaybeThisIsRu** [garritfra/seeking-maintainers.net#9]
### About the project

IndieWeb/microformats2 friendly blogging starter kit. Batteries packed.

### Why I need help

 I don't use Eleventy any more.

### Skills required

Be running their own Eleventy site. Be aware of the updates happening in that ecosystem. Microformats2 knowledge is beneficial but not necessary.

### How to get in touch

hello@rusingh.com

### Meta Information (Please fill out)

- [x] I have read the [FAQ section](https://seeking-maintainers.net/faq) and confirm that my project is eligible to be added to the list
- [x] The title of this issue only displays the name of my project
- [x] I have filled out the code snippet below

```yaml
# A link to the code repository or homepage of the project
url: "https://github.com/MaybeThisIsRu/smix-eleventy-starter"

# A short description of your project. The description text of your GitHub repo might fit here nicely
description: " A standards-respecting starter kit for Eleventy. Go Indie. "

# Some comma separated tags that describe your project (not yet implemented, but coming soon!)
tags: [eleventy, starter-kit, microformats2, indieweb]
```
